services:
  frontend:
    build: ./frontend/.
    ports:
      - "3000:3000"
    networks:
      - app-network

  backend:
    build: ./backend/.
    ports:
      - "5000:5000"
    networks:
      - app-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    build: ./db/.
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: